#!/usr/bin/env python3
"""Keeps SATURN_REWRITE_CHECKLIST.md honest.

  saturn_checklist.py scan     rewrite SATURN_TODO_INVENTORY.md and the note table of the
                               checklist from the source (run it after every change)
  saturn_checklist.py check    fail when either of them no longer matches the source, or
                               when a commit changes Saturn sources without the checklist
                               (used by the pre-commit hook, see install-hook)
  saturn_checklist.py install-hook   install the pre-commit hook in this repository

The hand-written part of the checklist says what each note means and what is done.
Everything with a line number is generated here, so it cannot go stale.
"""
import glob
import os
import re
import subprocess
import sys

ROOT = subprocess.check_output(["git", "rev-parse", "--show-toplevel"], text=True).strip()
CHECKLIST = "SATURN_REWRITE_CHECKLIST.md"
INVENTORY = "SATURN_TODO_INVENTORY.md"
BEGIN = "<!-- BEGIN GENERATED: note counts (scripts/saturn_checklist.py scan) -->"
END = "<!-- END GENERATED -->"

# every file the Saturn and ST-V machines use; a path that does not exist is an error, so a
# rename cannot silently drop a file from the inventory
SOURCES = [
    "src/mame/sega/sat_console.cpp", "src/mame/sega/saturn*.cpp", "src/mame/sega/saturn*.h",
    "src/mame/sega/stv*.cpp", "src/mame/sega/stv*.h", "src/mame/sega/smpc.*",
    "src/mame/sega/315_5649.*", "src/mame/sega/315-5881_crypt.*", "src/mame/sega/315-5838_317-0229_comp.*",
    "src/mame/sega/segabill.*",
    "src/devices/cpu/sh/sh2.*", "src/devices/cpu/sh/sh2fe.*", "src/devices/cpu/sh/sh7604*",
    "src/devices/cpu/sh/sh7032.*", "src/devices/cpu/sh/sh7014*",
    "src/devices/cpu/scudsp/*",
    "src/devices/sound/scsp*", "src/devices/sound/cdda.*", "src/mame/shared/rax.*",
    "src/devices/bus/sat_ctrl/*", "src/devices/bus/saturn/*",
    "src/devices/machine/nvram.cpp", "src/devices/machine/ticket.cpp", "src/devices/machine/eepromser.cpp",
    "src/lib/util/cdrom.cpp",
]
# a change under these paths needs the checklist in the same commit
WATCHED = re.compile(r"^(src/mame/sega/(sat|stv|smpc|315|segabill)|src/devices/cpu/(sh/sh(2|7604|7032|7014)|scudsp/)|"
                     r"src/devices/sound/(scsp|cdda)|src/mame/shared/rax|src/devices/bus/(sat_ctrl|saturn)/)")
NOTE = re.compile(r"TODO|FIXME|XXX|HACK|[Hh]ack|kludge|\bguess|getenv")


def sources():
    files = []
    for pattern in SOURCES:
        found = sorted(glob.glob(os.path.join(ROOT, pattern)))
        if not found:
            sys.exit(f"saturn_checklist: nothing matches {pattern}: update SOURCES")
        files += found
    return sorted(set(os.path.relpath(f, ROOT).replace(os.sep, "/") for f in files))


def notes():
    result = {}
    for rel in sources():
        with open(os.path.join(ROOT, rel), encoding="utf-8", errors="replace") as f:
            found = [(n, line.strip()) for n, line in enumerate(f, 1) if NOTE.search(line)]
        result[rel] = found
    return result


def inventory_text(found):
    out = ["# Saturn / ST-V source notes (generated)", "",
           "Generated by `scripts/saturn_checklist.py scan`. Do not edit: change the source, then run the script.",
           "Every line is a TODO / FIXME / XXX / HACK / hack / kludge / guess note or an environment variable diagnostic (getenv) in a file the Saturn or ST-V machines use.",
           "What each one means and what is done about it is in `SATURN_REWRITE_CHECKLIST.md`.", ""]
    for rel, items in found.items():
        if not items:
            continue
        out += [f"## {rel} ({len(items)})", ""]
        out += [f"- {n}: {text[:160].replace('|', '/')}" for n, text in items]
        out.append("")
    return "\n".join(out)


def table_text(found):
    rows = ["| File | Notes |", "|---|---|"]
    total = 0
    for rel, items in found.items():
        total += len(items)
        if items:
            rows.append(f"| `{rel}` | {len(items)} |")
    quiet = sum(1 for items in found.values() if not items)
    rows.append(f"| **{len(found) - quiet} files with notes, {quiet} searched files without** | **{total}** |")
    return "\n".join([BEGIN, ""] + rows + ["", END])


def read(name):
    path = os.path.join(ROOT, name)
    if not os.path.exists(path):
        return ""
    with open(path, encoding="utf-8", newline="") as f:
        return f.read().replace("\r\n", "\n")


def write(name, text):
    with open(os.path.join(ROOT, name), "w", encoding="utf-8", newline="\n") as f:
        f.write(text if text.endswith("\n") else text + "\n")


def with_table(checklist, table):
    pattern = re.compile(re.escape(BEGIN) + ".*?" + re.escape(END), re.S)
    if not pattern.search(checklist):
        sys.exit(f"saturn_checklist: {CHECKLIST} has no generated block: add the two marker lines")
    return pattern.sub(lambda m: table, checklist)


def scan():
    found = notes()
    write(INVENTORY, inventory_text(found))
    write(CHECKLIST, with_table(read(CHECKLIST), table_text(found)))
    print(f"{sum(len(v) for v in found.values())} notes in {len(found)} files written")


def staged():
    out = subprocess.check_output(["git", "diff", "--cached", "--name-only"], cwd=ROOT, text=True)
    return [l for l in out.splitlines() if l]


def check(hook):
    found = notes()
    problems = []
    if read(INVENTORY).strip() != inventory_text(found).strip():
        problems.append(f"{INVENTORY} does not match the source")
    if read(CHECKLIST) and with_table(read(CHECKLIST), table_text(found)).strip() != read(CHECKLIST).strip():
        problems.append(f"the note table in {CHECKLIST} does not match the source")
    if problems:
        problems.append("run: python scripts/saturn_checklist.py scan")
    if hook:
        files = staged()
        if any(WATCHED.match(f) for f in files) and CHECKLIST not in files:
            problems.append(f"this commit changes Saturn sources but not {CHECKLIST}: tick what is done, add what "
                            "the change found, set the 'Updated' line, run the scan, and `git add` both files")
    if problems:
        print("saturn checklist is stale:", *problems, sep="\n  ")
        return 1
    print("saturn checklist matches the source")
    return 0


def install_hook():
    git_dir = subprocess.check_output(["git", "rev-parse", "--git-common-dir"], cwd=ROOT, text=True).strip()
    hooks = os.path.join(os.path.abspath(os.path.join(ROOT, git_dir)), "hooks")
    path = os.path.join(hooks, "pre-commit")
    line = 'python "$(git rev-parse --show-toplevel)/scripts/saturn_checklist.py" check --hook || exit 1'
    old = open(path).read() if os.path.exists(path) else "#!/bin/sh\n"
    if "saturn_checklist.py" not in old:
        with open(path, "w", newline="\n") as f:
            f.write(old.rstrip("\n") + "\n" + line + "\n")
    print("hook installed:", path)


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else ""
    if cmd == "scan":
        scan()
    elif cmd == "check":
        sys.exit(check("--hook" in sys.argv))
    elif cmd == "install-hook":
        install_hook()
    else:
        sys.exit(__doc__)
